### ISSUE TITLE
which version of GATK should i use?

### ISSUE THREAD

**Issue by haoziyeung** [broadinstitute/deTiN#12]
Hello,i'm using gatk4,and i can't find AllelicCNV

java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /gpfs/users/yanghao/software/anaconda2/share/gatk4-4.0.3.0-0/gatk-package-4.0.3.0-local.jar AllelicCNV

A USER ERROR has occurred: 'AllelicCNV' is not a valid command.

can you tell me which version should i use? many thanks.

@amarotaylor

**Comment by amarotaylor** [comment]
I'm guessing you found this.. but linking here for others. Did not see this issue earlier sorry about that.
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.beta.6/org_broadinstitute_hellbender_tools_exome_AllelicCNV.php

**Comment by haoziyeung** [comment]
Many thanks.
