### ISSUE TITLE
generating inputs with GATK4

### ISSUE THREAD

**Issue by sraorao** [broadinstitute/deTiN#16]
Hi, apologies for cross-posting, I wonder if I can get some information regarding this from the deTiN team too. 

Is it possible to generate inputs for deTiN using GATK4 (4.0.6.0)? Specifically, is there a way to get the call-stats file from Mutect2 and is there an equivalent way to generate the SNP statistics file and aSCNV seg file using GATK 4.0.6.0? For example, do `f` and `tau` referred to here https://github.com/broadinstitute/deTiN/wiki/Description-of-inputs relate to `MINOR_ALLELE_FRACTION_POSTERIOR_50` and `LOG2_COPY_RATIO_POSTERIOR_50` respectively in GATK4 (4.0.6.0) ModelSegments output?

Thanks.

**Comment by amarotaylor** [comment]
Hi Sraorao,

No worries. Im not sure how to transform M2 callstats files into the M1 format. I recommend running MuTect1. DeTiN supports input from GATK 4.0.6.0 for the copy number data. You can just run as normal and deTiN will use MINOR_ALLELE_FRACTION_POSTERIOR_50 and LOG2_COPY_RATIO_POSTERIOR_50 automatically. GATK will generate a SNPs file for you:

https://gatkforums.broadinstitute.org/gatk/discussion/7719/overview-of-getbayesianhetcoverage-for-heterozygous-snp-calling

**Comment by Diogopell** [comment]
Wait! Doesn't the README https://github.com/broadinstitute/deTiN/blob/master/README.md it uses Mutect2 data?

**Comment by Diogopell** [comment]
So you used Mutext1 to create --mutation_data_path and Mutect2  to create  --indel_data_path?

**Comment by amarotaylor** [comment]
I agree it seems a bit weird. I've found that SSNV calls from M1 are superior to calls from M2. M2 is a pretty good indel caller though (Strelka is also good).
