### ISSUE TITLE
Description of outputs

### ISSUE THREAD

**Issue by MagdalenaZZ** [broadinstitute/deTiN#17]
Hi, 
it would be so nice if the content of the output files was described as comprehensively on the wiki as the content of the input files.
Especially for the text files the column headers it is not always completely clear what has been calculated there.

Thanks!!!

**Comment by amarotaylor** [comment]
Hey,

Good idea this is an oversight on my part. I will add that this week. 

Best
Amaro

**Comment by amarotaylor** [comment]
Added this now.
