### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by MagdalenaZZ** [broadinstitute/deTiN#18]
![screen shot 2018-10-18 at 10 14 38](https://user-images.githubusercontent.com/6588134/47144216-e4db5a00-d2be-11e8-9254-6aedec94b471.png)

Hi, I've run deTIN on a truth-set of artificially created TIN from 1-30%, for two samples. The results file is attached. Two thoughts; 
1. I seem to get higher score with aSCGC than with SSNV.
2. aSCG at very low levels of containation seem to report artificially high values.

Have you got any advice to offer to improve/interpret the results?

Also, I've noticed that even with 1% TIN contamination my SNV calling looses a lot of accuracy, do you believe deTIN can be tuned to discover such low levels of TIN?

Many thanks for your input!

**Comment by amarotaylor** [comment]
Hey Magalena,

Looks good overall though I agree that 1 and 2 look they could be issues. I think it might be easier for me to offer advice via a google hangout or longer emails. Can you drop me an email at amaro@broadinstitute.org so we can discuss? 

Best
Amaro
