### ISSUE TITLE
dbsnp/cosmic.vcf

### ISSUE THREAD

**Issue by petrsha** [broadinstitute/deTiN#19]
Hi, where can I get dbsnp_132_b37.leftAligned.vcf and hg19_cosmic_v54_120711.vcf, please? I tried wget http://archive.broadinstitute.org/cancer/cga/mutect/b37_cosmic_v54_120711.vcf and gsutil cp gs://firecloud-tcga-open-access/tutorial/reference/hg19/dbsnp_132_b37.leftAligned.vcf. I also looked on dbsnp and cosmic site but I didn't find it there.

**Comment by amarotaylor** [comment]
Hi
dbsnp vcf: gs://broad-references/hg19/v0/dbsnp_135.b37.vcf.gz
cosmic vcf: gs://firecloud-tcga-open-access/tutorial/reference/hg19_cosmic_v54_120711.vcf
