### ISSUE TITLE
Which version of GATK for CallCNLoHAndSplits

### ISSUE THREAD

**Issue by petrsha** [broadinstitute/deTiN#20]
Hi,
I run successfully AllelicCNV, but when I wanted to run the last step in this workflow (https://gatkforums.broadinstitute.org/gatk/discussion/7387/description-and-examples-of-the-steps-in-the-acnv-case-workflow) and generate a 'sim-final.acs.seg' file I found out that CallCNLoHAndSplits is not in the version GATK 4.beta.6.

**Comment by amarotaylor** [comment]
Hi I think its best to ask these GATK specific questions on their forum. Unfortunately I'm not aware of how they're restructuring their tools or what each release contains. I also have trouble keeping track.

**Comment by petrsha** [comment]
It seems it was only in an alpha release. Is there any other way to generate aSCNA segmentation file from the output of AllelicCNV, please?

**Comment by amarotaylor** [comment]
Does this article solve your issue?
https://software.broadinstitute.org/gatk/documentation/article?id=11683
