### ISSUE TITLE
Does deTiN support to accept SSNV and SCNA data from callers other than Mutect1 and AllelicCNV?

### ISSUE THREAD

**Issue by lindaxiang** [broadinstitute/deTiN#24]
Hi Amaro, 
Thank you for developing deTiN tool and we appreciate your great job!

My understanding is that as long as we can prepare the input files conforming to the required input definition and data format, deTiN should still have the capabilities to use the input data, train the models, estimate the TiN and do the inferences.  

So I am wondering if deTiN supports using SSNV/SCNA data from callers other than Broad's Mutect1 and allelicCNV?

For example, 
- For `mutation statistics file`,  if we follow the definition of the fields definition and we convert the SNV VCF results from either Sanger CaVEMan caller or Mutect2 to the `call-stats` format, I think the results of deTiN should still be valid, right?
- For `aSCNA segmentation file`, I was trying to find a mapping relationship between the CNV results from Sanger ASCAT caller and  required fields of `f`, `tau` and `n_probe` in segmentation file. However it is not that straightforward. Do you mind give us more information about how to generate those values from existing VCF files other than outputs from AllelicCNV? Or any suggestions are very appreciated. 

Thank again! 

-Linda

**Comment by amarotaylor** [comment]
Hey Linda,  

Nice to e-meet you. Happy to try and help out! DeTiN is method agnostic as long as you provide the required columns the model is valid. So the answer the first question is yes. Is there any chance you could send a list of headers from an ASCAT file? My guess is that ASCAT produces this information. f is the minor allele fraction covering a segment, tau is the copy ratio of the segment, and n_probes refers to the number of exome capture probes in the region (this could be generated using BEDtools).

Best
Amaro

**Comment by lindaxiang** [comment]
Hi Amaro,
Thank you so much for the swift response. Sorry for the delay reply. 
Firstly, thank you for the confirmation and we are very glad that the tool will also work for the data files from other callers. We will make some efforts to head for that direction then.

Secondly, ASCAT does produce multiple data files and the related are:

- SAMPLE.caveman.copynumber.csv has the columns:

| SegmentId|Chr|Start|End|Normal Major Allele Copy Number|Normal Minor Allele Copy Number|Tumour Major Allele Copy Number|Tumour Minor Allele Copy Number |
| ----------|-------|-------|--------|-------|------|------|------- |

- SAMPLE.copynumber.txt has the columns:

| SNP_identifier | Chromosome | Position | LogR  | segmented LogR | BAF | segmented BAF |  Copy number | Minor allele | Raw copy number |
| ----------|-------|-------|--------|-------|------|------|------- | -------| ------|

Note:
**LogR**: Normalized log transform of read depth (Tumour/Normal)
**BAF**: Allele Frequencies (Tumour/Normal)

For details, Please see the protocols paper,
https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/cpbi.17

Thanks again!
-Linda

**Comment by amarotaylor** [comment]
Hey Linda,

Great. I think tau corresponds to e(LogR) but centered at 2. BAF for the tumor should correspond directly to f (the min is 0 and max is 0.5?) . Hopefully that is helpful?

**Comment by lindaxiang** [comment]
Thank you Amaro. These information are very helpful!!
